apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: timescaledb
    url: timescaledb:5432
    user: crypto
    secureJsonData:
      password: crypto_secret
    jsonData:
      database: crypto
      sslmode: disable
      maxOpenConns: 5
      postgresVersion: 1600   # PostgreSQL 16
      timescaledb: true
    isDefault: true
    editable: false
